
name: Build

on: [push, pull_request, pull_request_target]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out
        uses: actions/checkout@v2

      - name: go vet
        run: go vet -mod=vendor ./...

      - name: Build
        run: go build -v -mod=vendor .

      - name: Test
        run: go test -race -cover -v -mod=vendor ./...
